title: Danish Mohd
email: d@supergeek.in
description: AI will change everything
url: "https://supergeek.in/"

permalink: /:slug.html
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - _pages


